node {
    stage("Checkout") {
        checkout scm
    }
    stage("Building image") {
        dir("attendance") {
            docker.build('${JOB_NAME}', '-f Dockerfile .')
        }
    }
    stage("Pushing image to ECR") {
        docker.withRegistry('390287378384.dkr.ecr.ap-southeast-1.amazonaws.com/vipin-1', 'spinnaker-registry') {
            docker.image('${JOB_NAME}').push('${BUILD_ID}')
        }
    }
}
